import { BUSINESS_EVALUATION_UNIT, BUSINESS_EVALUATION_UNIT_TOWN, BUSINESS_EVALUATION_UNIT_STREET } from '.';

export const groupsMap = {
  [BUSINESS_EVALUATION_UNIT_TOWN]: 'town',
  [BUSINESS_EVALUATION_UNIT_STREET]: 'dept',
  [BUSINESS_EVALUATION_UNIT]: 'pro'
};