import {
  BUSINESS_EVALUATION_UNIT,
  BUSINESS_EVALUATION_UNIT_TOWN,
  BUSINESS_EVALUATION_UNIT_STREET,
  BUSINESS_SCHEDULE_UNIT,
  BUSINESS_SCHEDULE_TOWN,
  BUSINESS_SCHEDULE_STREET,
  BUSINESS_TASK_UNIT,
  BUSINESS_TASK_TOWN,
  BUSINESS_TASK_STREET
} from '.';

export const groupsMap = {
  [BUSINESS_EVALUATION_UNIT_TOWN]: 'town',
  [BUSINESS_EVALUATION_UNIT_STREET]: 'dept',
  [BUSINESS_EVALUATION_UNIT]: 'pro',
  [BUSINESS_SCHEDULE_TOWN]: 'town',
  [BUSINESS_SCHEDULE_STREET]: 'dept',
  [BUSINESS_SCHEDULE_UNIT]: 'pro',
  [BUSINESS_TASK_TOWN]: 'town',
  [BUSINESS_TASK_STREET]: 'dept',
  [BUSINESS_TASK_UNIT]: 'pro'
};
